### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by lee-dohm** [msaraiva/atom-elixir#10]
### Repro Steps

1. Typing along in some code with the autocomplete panel popping up

**Atom Version**: 1.7.0-dev-e39d200
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-elixir](https://github.com/msaraiva/atom-elixir) package, v0.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/Lee/Source/atom-elixir/lib/elixir-autocomplete-provider.coffee:136

TypeError: Cannot read property 'replace' of undefined
    at module.exports.createSuggestionForFunction (/Users/Lee/Source/atom-elixir/lib/elixir-autocomplete-provider.coffee:136:23)
    at module.exports.createSuggestion (/Users/Lee/Source/atom-elixir/lib/elixir-autocomplete-provider.coffee:95:7)
    at /Users/Lee/Source/atom-elixir/lib/elixir-autocomplete-provider.coffee:69:11
    at Array.map (native)
    at /Users/Lee/Source/atom-elixir/lib/elixir-autocomplete-provider.coffee:64:35
    at ServerProcess.onResult (/Users/Lee/Source/atom-elixir/lib/server-process.coffee:75:7)
    at Socket.<anonymous> (/Users/Lee/Source/atom-elixir/lib/server-process.coffee:29:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
  3x -0:41.6.0 editor:move-to-beginning-of-word (atom-text-editor.path-input.editor.mini.is-focused)
     -0:40.6.0 editor:select-to-beginning-of-word (atom-text-editor.path-input.editor.mini.is-focused)
     -0:39.2.0 editor:move-to-end-of-screen-line (atom-text-editor.path-input.editor.mini.is-focused)
  2x -0:35.9.0 core:backspace (atom-text-editor.path-input.editor.mini.is-focused)
     -0:33.7.0 core:confirm (atom-text-editor.path-input.editor.mini.is-focused)
  3x -0:32.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.2.0 editor:newline (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:23.3.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:21.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:21.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:20.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:20.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:20.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "text.xml.plist": [
        "plist"
      ]
    },
    "disabledPackages": [
      "spell-check-test",
      "autocomplete-elixir",
      "autocomplete-erlang"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      ".keep",
      "._*",
      "*.pyc",
      "Thumbs.db"
    ],
    "projectHome": "/Users/Lee/Source",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.14.2
atom-elixir, v0.0.0
autocomplete-paths, v1.0.2
block-travel, v1.0.4
bug-report, v0.7.1
docblockr, v0.7.3
file-type-icons, v0.7.4
hex, v0.6.2
highlight-selected, v0.11.2
hyperclick, v0.0.35
indentation-indicator, v0.6.0
language-asciidoc, v0.12.0
language-elixir, v0.11.1
language-erlang, v3.0.0
language-generic-config, v1.0.0
language-haml, v0.23.15
language-jade, v0.6.3
language-mediawiki, v2.0.0
language-nginx, v0.6.1
language-r, v0.4.0
language-swift, v0.4.0
language-todotxt, v0.6.1
language-treetop, v0.1.3
minimap, v4.19.0
package-sync, v1.0.0
pigments, v0.24.1
red-wavy-underline, v0.3.0
set-syntax, v0.3.0
soft-wrap-indicator, v0.7.0
tabs-to-spaces, v1.0.2
word-jumper, v0.3.0

# Dev
autocomplete-plus, v2.27.1
```

**Comment by cameronp** [comment]
I get this consistently when typing "use ExUnit.Case" at the top of a new test file.  Haven't seen it happen any other time.





1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-elixir](https://github.com/msaraiva/atom-elixir) package, v0.0.4


### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Users/cameronp/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:136

TypeError: Cannot read property 'replace' of undefined
    at module.exports.createSuggestionForFunction (/Users/cameronp/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:136:23)
    at module.exports.createSuggestion (/Users/cameronp/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:95:7)
    at /Users/cameronp/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:69:11
    at Array.map (native)
    at /Users/cameronp/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:64:35
    at ServerProcess.onResult (/Users/cameronp/.atom/packages/atom-elixir/lib/server-process.coffee:75:7)
    at Socket.<anonymous> (/Users/cameronp/.atom/packages/atom-elixir/lib/server-process.coffee:29:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -0:39.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:39.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:39.9.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:35.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.8.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -0:34.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:34.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:34.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:33.9.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:29 core:close (atom-text-editor.editor.is-focused)
     -0:16.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:00.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-elixir, v0.0.4
autocomplete-erlang, v1.1.1
emmet, v2.4.1
language-elixir, v0.11.1
language-elm, v1.3.2
language-erlang, v3.0.0
react, v0.14.1

# Dev
No dev packages
```

**Comment by msaraiva** [comment]
Fixed!

**Comment by msaraiva** [comment]
And thanks for the detailed report :)
