### ISSUE TITLE
Failed to load - cannot find module 'marked'

### ISSUE THREAD

**Issue by blackfist** [msaraiva/atom-elixir#14]
[Enter steps to reproduce below:]

1. navigate to ~/.atom/packages
2. git clone this repo
3. Quit and re-open atom

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-elixir](https://github.com/msaraiva/atom-elixir) package, v0.0.3

### Stack Trace

Failed to load the atom-elixir package

```
At Cannot find module 'marked'

Error: Cannot find module 'marked'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevin.thompson/.atom/packages/atom-elixir/lib/utils.coffee:3:10)
    at Object.<anonymous> (/Users/kevin.thompson/.atom/packages/atom-elixir/lib/utils.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevin.thompson/.atom/packages/atom-elixir/lib/server-process.coffee:3:20)
    at Object.<anonymous> (/Users/kevin.thompson/.atom/packages/atom-elixir/lib/server-process.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kevin.thompson/.atom/packages/atom-elixir/lib/atom-elixir.coffee:3:17)
    at Object.<anonymous> (/Users/kevin.thompson/.atom/packages/atom-elixir/lib/atom-elixir.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-elixir, v0.0.3
autocomplete-ruby, v0.1.0
file-icons, v1.6.15
isotope-ui, v2.7.1
language-elixir, v0.11.1
language-erlang, v3.0.0
linter, v1.11.3
linter-python-pep8, v0.2.0

# Dev
No dev packages
```

**Comment by msaraiva** [comment]
You've missed the `apm install` inside the newly created folder, after cloning.

**Comment by blackfist** [comment]
ugh. Sorry. I am the dumb. Here is a funny gif as my way of saying sorry.

http://i.giphy.com/10C5xbZwvsFs64.gif

**Comment by msaraiva** [comment]
:)
