### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by fergusmeiklejohn** [msaraiva/atom-elixir#18]
[Enter steps to reproduce below:]

1. ...Threw error on install
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-elixir](https://github.com/msaraiva/atom-elixir) package, v0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

```
At /Users/fergus/.atom/packages/atom-elixir/lib/server-process.coffee:150

TypeError: Cannot read property 'stdin' of null
    at ServerProcess.module.exports.ServerProcess.sendRequest (/Users/fergus/.atom/packages/atom-elixir/lib/server-process.coffee:150:12)
    at ServerProcess.module.exports.ServerProcess.setEnv (/Users/fergus/.atom/packages/atom-elixir/lib/server-process.coffee:136:8)
    at /Users/fergus/.atom/packages/atom-elixir/lib/atom-elixir.coffee:38:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-elixir, v0.1.1
iex, v0.9.27
language-elixir, v0.12.3
linter, v1.11.3
linter-elixirc, v1.1.5

# Dev
No dev packages
```

**Comment by msaraiva** [comment]
@fergusmeiklejohn I've just published a new version v0.1.2. Can you try it out?

Thanks.

**Comment by fergusmeiklejohn** [comment]
thanks!  I installed v0.1.2, I don't get this error message anymore.  It doesn't seem work at all though.  None of the commands have any effect :-(
How can I help you debug this?

**Comment by msaraiva** [comment]
The server is probably not starting. Try this instructions and let me know the results.
https://github.com/msaraiva/atom-elixir/issues/19#issuecomment-194031815

**Comment by msaraiva** [comment]
Could you copy & paste the output of your console? You can use `alt+cmd+i` to open it.

**Comment by msaraiva** [comment]
@fergusmeiklejohn No need to send the output anymore. Thanks.
