### ISSUE TITLE
Cannot read property 'getDocumentation' of null

### ISSUE THREAD

**Issue by vdaniuk** [msaraiva/atom-elixir#3]
Was really looking forward to advanced elixir support in atom, thanks for making it a reality!

I've been testing and getting this error both on atom start and feature activating in editor. Atom is updated to latest version. I'm on Ubuntu 15.04.

```
TypeError: Cannot read property 'getDocumentation' of null
  at ElixirDocsProvider.module.exports.ElixirDocsProvider.addViewForElement (/home/rangeomorph/.atom/packages/atom-elixir/lib/elixir-docs-provider.coffee:65:12)
  at ElixirDocsProvider.module.exports.ElixirDocsProvider.showElixirDocs (/home/rangeomorph/.atom/packages/atom-elixir/lib/elixir-docs-provider.coffee:55:8)
  at atom-text-editor.<anonymous> (/home/rangeomorph/.atom/packages/atom-elixir/lib/elixir-docs-provider.coffee:25:8)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
  at /opt/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:544:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:363:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by msaraiva** [comment]
@vdaniuk if you hit `ctrl-shift-i` to open the dev/debug panel, do you see any message from the server?

**Comment by vdaniuk** [comment]
yep, 3 exceptions in addition to the original one:
```
GET https://atom.io/api/packages/atom-elixir 404 (Not Found)         /opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:8630 
undefined        /opt/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:51 
undefined        /opt/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:52
```

**Comment by msaraiva** [comment]
Just pushed a fix to master. Can you pull the package again and restart Atom? In your dev/debug view, you should see now:
```
[atom-elixir] Initializing alchemist-server (Elixir version 1.2.0)
```
If you don't, let me know.

**Comment by vdaniuk** [comment]
Atom-elixir alchemist notification is logged at Atom start, everything seems to be working as intended. Thanks for the fast fix.
