### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /\|>\s*??$/: Nothing to repeat

### ISSUE THREAD

**Issue by olivermt** [msaraiva/atom-elixir#32]
I was simply editing around when I got this error:

(This submit directly from atom thing is awesome)

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home Insider Preview
**Thrown From**: [atom-elixir](https://github.com/msaraiva/atom-elixir) package, v0.1.4

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /\|>\s*??$/: Nothing to repeat

```
At /C:/Users/olivermt/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:51

SyntaxError: Invalid regular expression: /\|>\s*??$/: Nothing to repeat
    at new RegExp (native)
    at RegExp (native)
    at ElixirAutocompleteProvider.module.exports.ElixirAutocompleteProvider.getSuggestions (file:///C:/Users/olivermt/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:35:43)
    at C:\Users\olivermt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\olivermt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\olivermt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\olivermt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:276:19)
    at C:\Users\olivermt\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
```

### Commands

```
     -0:32.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:30.5.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -0:29.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:22.1.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:21.2.0 editor:delete-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:19.6.0 core:delete (atom-text-editor.editor.is-focused)
  5x -0:09.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [],
    "projectHome": "C:\\Users\\olivermt\\Documents\\code"
  }
}
```

### Installed Packages

```coffee
# User
atom-elixir, v0.1.4
git-control, v0.7.1
language-elixir, v0.13.1
language-groovy, v0.6.0
Sublime-Style-Column-Selection, v1.5.1

# Dev
No dev packages
```

**Comment by msaraiva** [comment]
I can't reproduce this problem. Are you getting this error many times or was it only this once?

**Comment by olivermt** [comment]
Was only once and I later in the day had a weird git bug that made me have
to reboot to access a folder. Running on the linux enabled win10 preview,
so I guess we can likely attribute it to that.

**Comment by brennana** [comment]
This seems to still be a bug in this package.

Starting with the code:

```elixir
defmodule MyMod do
  def fun? do
  end
end
```
I find that the error is thrown each time I add an additional `?` to the end of the function name. The error is also thrown if I type `??` or more on a line.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: "Manjaro Linux"
**Thrown From**: [atom-elixir](https://github.com/msaraiva/atom-elixir) package 0.2.3


### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /\|>\s*fun???$/: Nothing to repeat

```
At /home/me/.atom/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:55

SyntaxError: Invalid regular expression: /\|>\s*fun???$/: Nothing to repeat
    at RegExp (<anonymous>)
    at ElixirAutocompleteProvider.module.exports.ElixirAutocompleteProvider.getSuggestions (/packages/atom-elixir/lib/elixir-autocomplete-provider.coffee:55:43)
    at providers.forEach.provider (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:268:52)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:244:15)
    at AutocompleteManager.findSuggestions (/usr/lib/atom/node_modules/autocomplete-plus/lib/autocomplete-manager.js:236:17)
```

### Commands

```
     -9:31.6.0 core:backspace (input.hidden-input)
     -9:30.3.0 atom-elixir:autocomplete-enter (input.hidden-input)
     -9:30.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:30.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -9:27.6.0 snippets:next-tab-stop (input.hidden-input)
     -9:26 atom-elixir:autocomplete-enter (input.hidden-input)
     -9:26 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -9:25.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:28.2.0 intentions:highlight (input.hidden-input)
     -6:27.7.0 settings-view:open (input.hidden-input)
  6x -6:19.5.0 core:backspace (input.hidden-input)
     -2:59.6.0 intentions:highlight (input.hidden-input)
     -2:59.6.0 core:select-all (input.hidden-input)
     -2:59.3.0 intentions:highlight (input.hidden-input)
     -2:59.2.0 core:copy (input.hidden-input)
     -2:54.9.0 core:move-left (input.hidden-input)
```

**Comment by AndrewDryga** [comment]
@msaraiva Here is sample code to reproduce the issue:
```
def book_trip(attrs) do
  Repo.transaction(fn ->
    with {:ok, exchange_rates} <- BillingAPI.fetch_currency_exchange_rates(attrs),
         {:ok, card_authorization} <- BillingAPI.authorize_card(exchange_rates, attrs),
         {:ok, hotel_booking} <- HotelBookingAPI.book_hotel(attrs),
         send_email_confirmation(card_authorization, hotel_booking, attrs),
         {:ok, charge} <- BillingAPI.charge_card(card_authorization) do
      {:ok, %{charge: charge, bookings: [hotel_booking]}}
    else
      {:error, {:authorization_expired, authorization}} ->
        :ok = send_excuse_email(authorization)
        :ok = cancel_booking(...) # Type question marks here instead of dots
        {:error, authorization}

      other ->
        other
    end
  end)
end
```
