### ISSUE TITLE
Auto-Completion stop working sometime

### ISSUE THREAD

**Issue by CalixHu** [msaraiva/atom-elixir#66]
I randomly got this error when I use the atom-elixir package. I have to restart the Atom to make it working again.
Here is the log:

[atom-elixir] Activating atom-elixir version 0.2.2
[atom-elixir] Initializing ElixirSense server for environment "test" (Elixir version 1.3.3)
Working directory is "/home/calixhu/workspace/abs"

[atom-elixir] ** (throw) {:expand_error, "Cannot expand recursive macro"}
    /home/calixhu/.atom/packages/atom-elixir/lib/elixir_sense/lib/elixir_sense/core/ast.ex:102: ElixirSense.Core.Ast.do_expand_with_fixes/2
    (elixir) lib/macro.ex:276: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:282: Macro.do_traverse/4
    (elixir) lib/macro.ex:277: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:282: Macro.do_traverse/4

[atom-elixir] Child process exited with code 1
Uncaught (in promise) TypeError: Cannot read property 'stdin' of null(…)
Server busy! 

Thanks.

**Comment by msaraiva** [comment]
@CalixHu It would be great if you could reproduce this error and send more information about the context. This kind of error is not supposed to be random. It should happen every time when you try to call the same action in the same context, i.e. file, line and column.

**Comment by CalixHu** [comment]
I think I can reproduce this.
1. Open a unit test file.
2. Typing something.
3. It will throw this error
![123](https://cloud.githubusercontent.com/assets/15894325/23350630/d2e9d212-fcf6-11e6-811c-d6f9f18e5fe2.jpg)
:
