### ISSUE TITLE
Can't run apm install

### ISSUE THREAD

**Issue by vanloc0301** [msaraiva/atom-elixir#7]
I was clone project to atom package folder.
But when I open the terminal and run `apm install` was not install on my machine.
I must set up apmd but it was not run.

I was run command `atom-beta install` it show error like:
`
Failed to load the atom-elixir package

```
At Cannot find module 'marked'

Error: Cannot find module 'marked'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dapi/.atom/packages/atom-elixir/lib/utils.coffee:3:10)
    at Object.<anonymous> (/home/dapi/.atom/packages/atom-elixir/lib/utils.coffee:1:1)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dapi/.atom/packages/atom-elixir/lib/server-process.coffee:3:20)
    at Object.<anonymous> (/home/dapi/.atom/packages/atom-elixir/lib/server-process.coffee:1:1)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dapi/.atom/packages/atom-elixir/lib/atom-elixir.coffee:3:17)
    at Object.<anonymous> (/home/dapi/.atom/packages/atom-elixir/lib/atom-elixir.coffee:1:1)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom-beta/resources/app.asar/src/package.js:720:27)
```
`
My computer run ubuntu 14.04 LTS.
Thanks.

**Comment by vanloc0301** [comment]
Updated, I forget run command `npm install` before run `atom-beta install`.
