### ISSUE TITLE
Expand and quote do nothing

### ISSUE THREAD

**Issue by paradox460** [msaraiva/atom-elixir#82]
I select a use block, and run Atom Elixir: Expand. Nothing happens. Looking into my atom console shows the following error, from `elixir-expand-view.coffee [sm]:62`

```
Uncaught (in promise) TypeError: Cannot read property 'destroy' of undefined
    at ElixirExpandedView.module.exports.ElixirExpandedView.initialize (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-view.coffee:62:80)
    at ElixirExpandedView.View [as constructor] (/Users/jeff.sandberg/.atom/packages/autocomplete-bibtex/node_modules/space-pen/lib/space-pen.js:184:25)
    at ElixirExpandedView.ScrollView [as constructor] (/Users/jeff.sandberg/.atom/packages/autocomplete-bibtex/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ElixirExpandedView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-view.coffee:56:5)
    at createElixirExpandView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-provider.coffee:8:7)
    at /Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-provider.coffee:42:9
    at Workspace.createItemForURI (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1327:28)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1133:42)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:449
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:105)
    at ElixirExpandProvider.module.exports.ElixirExpandProvider.addView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-provider.coffee:67:20)
    at ElixirExpandProvider.module.exports.ElixirExpandProvider.showExpandCodeView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-provider.coffee:62:6)
    at HTMLElement.<anonymous> (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-expand-provider.coffee:29:8)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

I get similar errors whenever I attempt to use the quote function:

```
Uncaught (in promise) TypeError: Cannot read property 'destroy' of undefined
    at ElixirQuotedView.module.exports.ElixirQuotedView.initialize (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-view.coffee:82:73)
    at ElixirQuotedView.View [as constructor] (/Users/jeff.sandberg/.atom/packages/autocomplete-bibtex/node_modules/space-pen/lib/space-pen.js:184:25)
    at ElixirQuotedView.ScrollView [as constructor] (/Users/jeff.sandberg/.atom/packages/autocomplete-bibtex/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new ElixirQuotedView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-view.coffee:61:5)
    at createElixirQuotedView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-provider.coffee:8:7)
    at /Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-provider.coffee:40:9
    at Workspace.createItemForURI (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1327:28)
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:1133:42)
    at Generator.next (<anonymous>)
    at step (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:279)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:449
    at Workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:11:105)
    at ElixirQuotedProvider.module.exports.ElixirQuotedProvider.addView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-provider.coffee:74:20)
    at ElixirQuotedProvider.module.exports.ElixirQuotedProvider.showQuotedCodeView (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-provider.coffee:69:6)
    at HTMLElement.<anonymous> (/Users/jeff.sandberg/.atom/packages/atom-elixir/lib/elixir-quoted-provider.coffee:27:8)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
module.exports.ElixirQuotedView.initialize @ elixir-quoted-view.coffee [sm]:82
View @ /Users/jeff.sandberg/.atom/packages/autocomplete-bibtex/node_modules/space-pen/lib/space-pen.js:184
ScrollView @ /Users/jeff.sandberg/.atom/packages/autocomplete-bibtex/node_modules/atom-space-pen-views/lib/scrol…:12
ElixirQuotedView @ elixir-quoted-view.coffee [sm]:61
createElixirQuotedView @ elixir-quoted-provider.coffee [sm]:8
(anonymous) @ elixir-quoted-provider.coffee [sm]:40
createItemForURI @ <embedded>:28915
(anonymous) @ <embedded>:28721
step @ <embedded>:27599
(anonymous) @ <embedded>:27599
(anonymous) @ <embedded>:27599
module.exports.ElixirQuotedProvider.addView @ elixir-quoted-provider.coffee [sm]:74
module.exports.ElixirQuotedProvider.showQuotedCodeView @ elixir-quoted-provider.coffee [sm]:69
(anonymous) @ elixir-quoted-provider.coffee [sm]:27
handleCommandEvent @ <embedded>:23414
didConfirmSelection @ <embedded>:44420
confirmSelection @ <embedded>:98516
core:confirm @ <embedded>:98221
handleCommandEvent @ <embedded>:23414
module.exports.KeymapManager.dispatchCommandEvent @ <embedded>:69803
module.exports.KeymapManager.handleKeyboardEvent @ <embedded>:69594
handleDocumentKeyEvent @ <embedded>:19289
```

**Comment by mennanov** [comment]
I'm having the same issue.
Any workarounds?

**Comment by AndrewDryga** [comment]
Same here.

**Comment by richardpringle** [comment]
+1
