### ISSUE TITLE
Callback must be a function

### ISSUE THREAD

**Issue by bmfay** [msaraiva/atom-elixir#85]
I can't seem to get any of this packages features to work.  It seems to be building fine as I am seeing 

```
[atom-elixir] Initializing ElixirSense server for environment "dev" (Elixir version 1.5.3)

/Users/bmfay/.atom/packages/atom-elixir/lib/server-process.coffee:76 [atom-elixir] Working directory is "/Users/bmfay/work/new-api"
```

But I can't get autocomplete to work and am seeing this error many times over in the console:

```
callback must be a function
    at makeCallback (fs.js:165:11)
    at Object.fs.unlink (fs.js:1048:14)
    at ServerProcess.<anonymous> (/Users/bmfay/.atom/packages/atom-elixir/lib/server-process.coffee:83:10)
    at Socket.<anonymous> (/Users/bmfay/.atom/packages/atom-elixir/lib/server-process.coffee:35:12)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

Any ideas?

**Comment by gpad** [comment]
I try to fix it locally but all the things (the code inside ATOM) and the
part in elixir is very outdated and it's not maintained properly ... I
don't know if there is another package similar to this or if the author
wants update this ...


Il giorno mar 17 set 2019 alle ore 00:40 Brendan Fay <
notifications@github.com> ha scritto:

**Comment by hieu-yojee** [comment]
I have the same problem. :((

**Comment by jackd942** [comment]
Same here as well.

**Comment by mhyrr** [comment]
Getting the same thing, seems to happen any time an autocomplete lookup is attemped.

On Elixir 1.9.4

**Comment by mindok** [comment]
me too. On windows, Atom v1.41.0

**Comment by TylerTemp** [comment]
Same here on Mac, elixir-1.10.2, Erlang/OTP 22 [erts-10.7.1], atom-elixir 0.2.3

```
$ atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
